Repository zip-rs/zip2, pull requests merged in 2024-05, with the labels that each got.

#82 feat: Add support for extended timestamps
  src/extra_fields/extended_timestamp.rs
  src/extra_fields/mod.rs
  src/lib.rs
  src/read.rs
  src/types.rs
  src/write.rs
  tests/data/extended_timestamp.zip
  tests/zip_extended_timestamp.rs
Labels: waiting-to-be-merged

#78 refactor: use displaydoc and thiserror to remove some boilerplate
  Cargo.toml
  src/result.rs
  src/write.rs
Labels: waiting-to-be-merged

#76 feat: add ZipWriter::merge_archive() to efficiently copy all entries from a ZipArchive
  Cargo.toml
  benches/merge_archive.rs
  src/read.rs
  src/write.rs
Labels: waiting-to-be-merged

#77 refactor: use num_enum to clean up the System type
  Cargo.toml
  src/read.rs
  src/types.rs
Labels: waiting-to-be-merged

#75 feat: add ZipWriter::finish_into_readable()
  src/read.rs
  src/write.rs
Labels: waiting-to-be-merged

#84 Remove unnecessary "mut"
  src/aes_ctr.rs
Labels: waiting-to-be-merged

#55 doc: add append example
  README.md
  examples/append.rs
Labels: waiting-to-be-merged

#91 perf: use indexmap in read::zip_archive::Shared instead of a separate vec and hashmap
  Cargo.toml
  src/read.rs
  src/write.rs
Labels: waiting-to-be-merged

#67 doc: new example to show how to write large files (greater than 4GB)
  examples/write-large-file.rs
Labels: waiting-to-be-merged

#92 ci: Run cargo doc and clippy with default features, all features and no features
  .github/workflows/ci.yaml
  benches/merge_archive.rs
Labels: waiting-to-be-merged

#95 perf: Speedup path_to_string when path is already in the correct format
  src/spec.rs
Labels: waiting-to-be-merged

#96 Use clap to parse args and add compression method argument in write_dir example
  Cargo.toml
  examples/write_dir.rs
Labels: waiting-to-be-merged

#98 refactor: Make `ZipWriter::finish()` consume the `ZipWriter`
  benches/merge_archive.rs
  fuzz/Cargo.toml
  fuzz/fuzz_targets/fuzz_write.rs
  src/write.rs
  tests/zip_crypto.rs
Labels: waiting-to-be-merged

#97 chore: release v1.2.0
  CHANGELOG.md
  Cargo.toml
Labels: release

#80 Add AES encryption write support
  Cargo.toml
  examples/write_sample.rs
  fuzz/fuzz_targets/fuzz_write.rs
  src/aes.rs
  src/lib.rs
  src/read.rs
  src/types.rs
  src/unstable.rs
  src/write.rs
  src/zipcrypto.rs
  tests/aes_encryption.rs
Labels: waiting to be automatically merged

#103 chore: release v1.2.1
  CHANGELOG.md
  Cargo.toml
Labels: release

#101 Remove `num_enum`
  Cargo.toml
  src/types.rs
Labels: waiting to be automatically merged

#104 chore: release v1.2.2
  CHANGELOG.md
  Cargo.toml
Labels: release

#106 fix: UTF-8 flag could be set for non-UTF8 filenames
  src/write.rs
  tests/data/non_utf8.zip
Labels: waiting to be automatically merged

#118 chore: release v1.2.3
  CHANGELOG.md
  Cargo.toml
Labels: release

#131 chore: release v1.3.0
  CHANGELOG.md
  Cargo.toml
Labels: release

#137 doc: Enable all features for Docs.rs
  .github/workflows/ci.yaml
  Cargo.toml
  README.md
Labels: waiting to be automatically merged

#140 chore: release v1.3.1
  CHANGELOG.md
  Cargo.toml
Labels: release

#141 chore: Add `since` to `deprecated`
  src/types.rs
Labels: waiting to be automatically merged

#142 Implement `PartialEq`, `Eq`, `PartialOrd`, `Ord`, `Hash` and `Display` for `DateTime`
  src/types.rs
Labels: waiting to be automatically merged

#143 feat: Expose AES information
  src/aes.rs
  src/read.rs
Labels: waiting to be automatically merged

#147 chore: release v2.0.0
  CHANGELOG.md
  Cargo.toml
Labels: release, waiting to be automatically merged

#93 perf: parse headers in blocks and scan for magic numbers with memchr
  Cargo.toml
  benches/read_metadata.rs
  src/compression.rs
  src/read.rs
  src/read/stream.rs
  src/spec.rs
  src/types.rs
  src/write.rs
  tests/data/misaligned_comment.zip
  tests/zip_comment_garbage.rs
Labels: waiting to be automatically merged, major

#154 chore: release v2.1.0
  CHANGELOG.md
  Cargo.toml
Labels: release

#156 chore: release v2.1.1
  CHANGELOG.md
  Cargo.toml
Labels: release

#158 fix: Change `DateTime` to fully validate dates and discard inserted leap seconds
  src/types.rs
Labels: waiting to be automatically merged

#109 feat: Allow the archive offset behavior of the reader to be configured.
  src/read.rs
  src/read/config.rs
  src/write.rs
Labels: waiting to be automatically merged
