Repository zip-rs/zip2, pull requests merged in 2024-07, with the labels that each got.

#199 feat: Support XZ decompression
  Cargo.toml
  fuzz/fuzz.dict
  src/compression.rs
  src/lib.rs
  src/read.rs
  src/read/xz.rs
  src/types.rs
  src/write.rs
  tests/data/xz.zip
  tests/xz.rs
Labels: waiting to be automatically merged

#45 fix: Improve several `Read` methods on `ZipFile`
  src/crc32.rs
  src/read.rs
Labels: Please fix failing tests, no activity by author for 30 days

#212 refactor: Improve `FixedSizeBlock`
  src/read.rs
  src/spec.rs
  src/types.rs
Labels: waiting to be automatically merged

#66 feat: Add ZipWriter::set_file_metadata()
  src/write.rs
Labels: waiting to be automatically merged, no activity by author for 30 days

#69 feat: Add by_name_seek() for Stored zips
  fuzz/fuzz_targets/fuzz_write.rs
  src/lib.rs
  src/read.rs
Labels: waiting to be automatically merged, no activity by author for 30 days

#64 feat: Added function to get if a file is encrypted or not
  src/read.rs
Labels: waiting to be automatically merged, no activity by author for 30 days

#79 feat: publicly export and document the zip64 threshold constants
  src/lib.rs
  src/spec.rs
Labels: waiting to be automatically merged

#210 Multiple refactors
  src/compression.rs
  src/read.rs
  src/read/lzma.rs
  src/read/xz.rs
  src/write.rs
Labels: waiting to be automatically merged

#222 chore: release v2.1.5
  CHANGELOG.md
  Cargo.toml
Labels: release

#221 fix: (#33) Rare combination of settings could lead to writing a corrupt archive with overlength extra data, and data_start locations when reading the archive back were also wrong
  src/read.rs
  src/types.rs
  src/write.rs
Labels: help wanted, Please fix failing tests

#229 chore: release v2.1.6
  CHANGELOG.md
  Cargo.toml
Labels: release
